export const ValidationPattern = {
    EMAIL: '^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,}$',
    URL: '^(https?|ftp)://[\\w\\.-]+(:\\d+)?(/[\\w\\.-]*)*/?$',
    DATE: '^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(\\d{4})$',
    TIME: '^(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])(:([0-5][0-9]))?$',
    DATETIME: '^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(\\d{4}) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])(:([0-5][0-9]))?$',
    CPF: '^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$',
    CEP_BR: '^\\d{5}-\\d{3}$',
    RG: '^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9X]$',
    CNPJ: '^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$',
    CELULAR_BR: '^\\(\\d{2}\\) \\d{5}-\\d{4}$',
    TELEFONE_BR: '^\\(\\d{2}\\) \\d{4}-\\d{4}$',
    PHONE: '^\\(\\d{2}\\) \\d{4,5}-\\d{4}$',
    ONLY_NUMBERS: '^\\d+$',
    ONLY_NUMBERS_WITH_DASH: '^\\d+-?\\d+$',
    ONLY_LETTERS: '^[A-Za-zÀ-ÿ\\s]+$',
    ONLY_LETTERS_WITH_DASH: '^[A-Za-zÀ-ÿ\\s-]+$',
    ONLY_LETTERS_WITH_DASH_AND_NUMBERS: '^[A-Za-zÀ-ÿ\\s\\d-]+$',
    ONLY_LETTERS_WITH_NUMBERS: '^[A-Za-zÀ-ÿ\\d\\s]+$',
    ONLY_LETTERS_WITH_NUMBERS_AND_DASH: '^[A-Za-zÀ-ÿ\\d\\s-]+$',
    ONLY_LETTERS_WITH_NUMBERS_AND_UNDERSCORE: '^[A-Za-zÀ-ÿ\\d_\\s]+$',
    NAME_SIMPLE: '^[A-Za-zÀ-ÿ]{2,}$',
    NAME_WITH_SPACES: '^[A-Za-zÀ-ÿ\\s]{2,}$',
    FULL_NAME: '^[A-Za-zÀ-ÿ]+\\s[A-Za-zÀ-ÿ\\s]+$',
    FULL_NAME_WITH_PREPOSITIONS: '^[A-Za-zÀ-ÿ]+(?:\\s(?:da|de|do|das|dos|e|[A-Za-zÀ-ÿ])+)+$',
    NAME_WITH_APOSTROPHE: '^[A-Za-zÀ-ÿ\\\'\\s-]+$',
    NAME_WITH_SPECIAL_CHARS: '^[A-Za-zÀ-ÿ\\\'\\s\\-\\.]+$',
    INITIALS_WITH_LAST_NAME: '^(?:[A-Z]\\.\\s)*[A-Za-zÀ-ÿ]+(?:\\s[A-Za-zÀ-ÿ]+)+$',
    PASSPORT_BR: '^[A-Z]{2}[0-9]{6}$',
    PIS_PASEP: '^\\d{3}\\.\\d{5}\\.\\d{2}-\\d{1}$',
    TITULO_ELEITOR: '^\\d{4}\\.\\d{4}\\.\\d{4}$',
    CARTEIRA_TRABALHO: '^\\d{7,8}-\\d{1}$',
    REGISTRO_PROFISSIONAL: '^[A-Z]{2,3}-\\d{4,6}$',
    AGENCIA_BANCARIA: '^\\d{4}(-\\d{1})?$',
    CONTA_BANCARIA: '^\\d{5,12}(-\\d{1,2})?$',
    CODIGO_BANCO: '^\\d{3}$',
    ENDERECO_COMPLETO: '^[A-Za-zÀ-ÿ0-9\\s,.\\-]{10,}$',
    NUMERO_ENDERECO: '^\\d{1,6}([A-Za-z]|-\\d{1,3})?$',
    UUID: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    CODIGO_BARRAS_EAN13: '^\\d{13}$',
    CODIGO_BARRAS_BOLETO: '^\\d{44,48}$',
    CODIGO_RASTREIO_CORREIOS: '^[A-Z]{2}\\d{9}[A-Z]{2}$',
    PASSWORD_MEDIUM: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$',
    PASSWORD_STRONG: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).{10,}$',
    TOKEN_AUTH: '^[A-Za-z0-9-_]{20,}\\.[A-Za-z0-9-_]{20,}\\.[A-Za-z0-9-_]{20,}$',
    IP_V4: '^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$',
    IP_V6: '^(?:[A-F0-9]{1,4}:){7}[A-F0-9]{1,4}$',
    MAC_ADDRESS: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$',
    DOMAIN_NAME: '^([a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$',
    INSCRICAO_ESTADUAL: '^\\d{8,14}$',
    INSCRICAO_MUNICIPAL: '^\\d{8,15}$',
    PROCESSO_JUDICIAL: '^\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}$',
    PASSPORT_INTL: '^[A-Z0-9]{6,9}$',
    PHONE_INTL: '^\\+\\d{1,3}\\s?\\(\\d{1,3}\\)\\s?\\d{3,10}$',
    SSN_US: '^\\d{3}-\\d{2}-\\d{4}$',
    CUSTOM: '',
  } as const;

  export type ValidationPattern = typeof ValidationPattern[keyof typeof ValidationPattern];
